version: '2'
services:

  web:
    build: .
    working_dir: /viron
    depends_on:
      - api
    ports:
      - 8080:8080
    volumes:
      - ./.editorconfig:/viron/.editorconfig
      - ./.eslintrc.js:/viron/.eslintrc.js
      - ./.stylefmtrc:/viron/.stylefmtrc
      - ./.stylelintrc:/viron/.stylelintrc
      - ./package-lock.json:/viron/package-lock.json
      - ./package.json:/viron/package.json
      - ./postcss.config.js:/viron/postcss.config.js
      - ./public:/viron/public
      - ./rollup.base.config.js:/viron/rollup.base.config.js
      - ./rollup.config.js:/viron/rollup.config.js
      - ./rollup.local.config.js:/viron/rollup.local.config.js
      - ./src:/viron/src
      - ./task:/viron/task
      - ./test:/viron/test
    command: npm run start

  api:
    build: ./example-node
    working_dir: /example-node
    depends_on:
      - mysql
    ports:
      - 3000:3000
      - 53000:53000
    environment:
      - SERVICE_ENV=local
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
    volumes:
      - ./example-node/package.json:/example-node/package.json
      - ./example-node/shared:/example-node/shared
      - ./example-node/config:/example-node/config
      - ./example-node/app.js:/example-node/app.js
      - ./example-node/controllers:/example-node/controllers
      - ./example-node/fittings:/example-node/fittings
      - ./example-node/swagger:/example-node/swagger
      - ./example-node/test:/example-node/test
      - ./example-node/.env.template:/example-node/.env
    command: npm run debug

  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - $PWD/.docker/mysql/data:/var/lib/mysql
    env_file:
        - ./mysql.env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      default:
        aliases:
          - viron.dev
