version: '2'
services:

  example-go:
    # 240*1024*1024 = 251658240 Byte = 240 MB
    mem_limit: 251658240
    build: docker/local
    working_dir: "/go"
    depends_on:
      - mysql
    ports:
      - 3000:3000
      # realize
      - 5000:5000
      # goconvey
      - 4001:4001
    environment:
      - SERVICE_ENV=local
    volumes:
      - $PWD/dist/Linux:/go/dist/Linux
      - $PWD/src:/go/src
      - $PWD/Makefile:/go/Makefile
      - $PWD/cdep:/go/cdep
      - $PWD/cdep.conf:/go/cdep.conf
      - $PWD/cdep.lock:/go/cdep.lock
      - $PWD/realize.yaml:/go/realize.yaml
    command: make realize-docker
    #command: tail -f /var/log/bootstrap.log

  mysql:
    # 512*1024*1024 = 536870912 Byte = 512 MB
    mem_limit: 536870912
    build: docker/mysql
    ports:
      - 3306:3306
    volumes:
      - $PWD/docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dmc_local
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
